version: '3.8'  # Usa una versión más reciente

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Mejor práctica para node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:4000  # Usa el nombre del servicio
    command: ["npm", "start"]
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules  # Mejor práctica para node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/empresas
      - CORS_ORIGIN=http://localhost:3000
    command: ["npm", "run", "dev"]
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6.0  # Especifica versión
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=empresas
    networks:
      - app-network
    healthcheck:  # Añade healthcheck para MongoDB
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
    name: mongo-data  # Nombre explícito

networks:
  app-network:
    driver: bridge